### ISSUE TITLE
[Bug]: Windows Server crash when LAN is enable

### ISSUE THREAD

**Issue by TheEnergy** [kus/cs2-modded-server#97]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Windows 11

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

LAN off a machine on my local network

### Metamod:Source Version

0

### Metamod:Source Plugins loaded

0

### CounterStrikeSharp Version

0

### CounterStrikeSharp Plugins loaded

0

### What is the bug

When sv_lan is set to 1 the server crash on boot. Can't seems to find the output of the crash in logs. The server works fine when sv_lan is set to 0. So it seems to be something with LAN only. 

### Server log output

```shell
If you want to quit, close the CS2 window and type Y followed by Enter.
Using SteamCMD to check for updates.
Backup file server\game\csgo\gameinfo.gi already exists.
Checking if server\game\csgo\gameinfo.gi has already been patched...
server\game\csgo\gameinfo.gi has already been patched.
Copying mod files.
        1 file(s) copied.
Copying custom files from "custom_files".
CS2 started.
WARNING: CS2 closed or crashed.
Press any key to continue . . .
```

### Steps to reproduce

Windows 11
Download Github.
Follow instructions from github

You can either [Download this repo](https://github.com/kus/cs2-modded-server/archive/master.zip) and extract it
Create a folder steamcmd and [download SteamCMD](https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip) and extract it inside steamcmd so you should have \steamcmd\steamcmd.exe.

To download maps from the workshop, your server [needs access](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive/Dedicated_Servers#Steam_Workshop) to the Steam Web API. To allow this, open \win.ini and set cs_api_key to your [Steam Web API Key](http://steamcommunity.com/dev/apikey).

If setting up LAN server:

Copy \game\csgo\cfg\env.cfg to your [custom files](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#custom-files) directory \custom_files\cfg\env.cfg and set sv_lan to 1

[Add admins](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#acessing-admin-menu)

Run win.bat

**Comment by Mr-Robot-ops** [comment]
Have you tried to start win.bat with administrator rights?

**Comment by TheEnergy** [comment]
Yes, it works fine with sv_lan 0
And i cant find the reason, consol Window close to fast and no error in logs.

**Comment by kus** [comment]
Can you please try the latest update I just pushed? There was issues with Windows and now after this fix it works on my Windows machine.

**NOTE:** `win.bat` now deletes your `addons` folder to make sure no old plugins or files are there so if you have any custom files in there, you need to move to your [custom_files](https://github.com/kus/cs2-modded-server#custom-files) folder and mimic the directory structure. These are merged in at the end after download game updates and files from this mod.

Please let me know if this has fixed the issue for you.

**Comment by TheEnergy** [comment]
> Can you please try the latest update I just pushed? There was issues with Windows and now after this fix it works on my Windows machine.
> 
> **NOTE:** `win.bat` now deletes your `addons` folder to make sure no old plugins or files are there so if you have any custom files in there, you need to move to your [custom_files](https://github.com/kus/cs2-modded-server#custom-files) folder and mimic the directory structure. These are merged in at the end after download game updates and files from this mod.
> 
> Please let me know if this has fixed the issue for you.

I just downloaded and tried, still crash when sv_lan is 0 but works like a charm when sv_lan is 1.
The logs in CS2Server\SteamCMD\logs doesnt seems to have any relevativ information about the crash at all?

**Comment by kus** [comment]
This is extremely odd. Have you tried another computer on your lan joining when you have sv_lan 0? Maybe its not required - I just carried the settings over from CS:GO.

Although replicating your setup (following the base install on Windows 10, copying env.cfg and secrets.cfg to custom_files and changing sv_lan to 1) my server works fine.

**Comment by TheEnergy** [comment]
I have disabled the UAC in Windows 11 and now when i run it at administrator it actually works. 
This error does show when launching.

Attempting to create backup file of server\game\csgo\gameinfo.gi...
The system cannot find the path specified.
Backup file server\game\csgo\gameinfo.gi.bak created successfully.
Checking if server\game\csgo\gameinfo.gi has already been patched...
FINDSTR: Cannot open server\game\csgo\gameinfo.gi
server\game\csgo\gameinfo.gi needs to be patched...
The system cannot find the path specified.
Failed to create or modify temporary file server\game\csgo\gameinfo.gi.tmp. Potential access issue or write protection.
Deleting addons folder.
Copying mod files.
Merging Windows specific files.
Copying custom files from "".
Cannot perform a cyclic copy
CS2 started.

It still crash when not run as administrator.
But when sv_lan is 0 it does not crash. But the above error shows when launched as administrator also.
Location of the install is C:\CS2Server

"This is extremely odd. Have you tried another computer on your lan joining when you have sv_lan 0? Maybe its not required - I just carried the settings over from CS:GO."
Yes i have tried to join the server and it works and i can see it as a LAN Server, but i would like to have it private without password :-)

**Comment by TheEnergy** [comment]
Just made a clean Windows 10 install. 

Same thing happens when i run as administrator.

If you want to quit, close the CS2 window and type Y followed by Enter.
Using SteamCMD to check for updates.
Attempting to create backup file of server\game\csgo\gameinfo.gi...
The system cannot find the path specified.
Backup file server\game\csgo\gameinfo.gi.bak created successfully.
Checking if server\game\csgo\gameinfo.gi has already been patched...
FINDSTR: Cannot open server\game\csgo\gameinfo.gi
server\game\csgo\gameinfo.gi needs to be patched...
The system cannot find the path specified.
Failed to create or modify temporary file server\game\csgo\gameinfo.gi.tmp. Potential access issue or write protection.
Deleting addons folder.
Copying mod files.
Merging Windows specific files.
Copying custom files from "".
Cannot perform a cyclic copy
CS2 started.
WARNING: CS2 closed or crashed.
Press any key to continue . . .

**Comment by TheEnergy** [comment]
With SV_LAN 0 and runs as administrator. Server still starts, but gettings a few errors.

The following error only appears when runs as administrator.
"Attempting to create backup file of server\game\csgo\gameinfo.gi...
The system cannot find the path specified.
Backup file server\game\csgo\gameinfo.gi.bak created successfully.
Checking if server\game\csgo\gameinfo.gi has already been patched...
FINDSTR: Cannot open server\game\csgo\gameinfo.gi
server\game\csgo\gameinfo.gi needs to be patched...
The system cannot find the path specified.
Failed to create or modify temporary file server\game\csgo\gameinfo.gi.tmp. Potential access issue or write protection.
Deleting addons folder.
Copying mod files.
Merging Windows specific files.
Copying custom files from "".
Cannot perform a cyclic copy"

When Server starts following error show
"USRLOCAL path not found!"

"MOD desires lightbiner GPU but is unsupported by HW (SupportsCompute=0 CubeMapArrays=0)
Physics Console Communications is not initialized
No .vcds loaded or no scenes/scenes.vrman
GameTypes: missing nameID entry for game type/mode (classic/deathmatch).
GameTypes: missing descID entry for game type/mode (classic/deathmatch).
GameTypes: missing mapgroupsSP entry for game type/mode (classic/deathmatch).
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission)."

"Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\CounterStrikeSharp.API.dll - Access violation at 00007FFE5021AD7C accessing 000002112D011000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.dll - Access violation at 00007FFE5021AD7C accessing 00000210959A1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Hosting.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 00000210959B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.DependencyInjection.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 00000210959C1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Hosting.dll - Access violation at 00007FFE5021AD7C accessing 00000210959E1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Serilog.dll - Access violation at 00007FFE5021AD7C accessing 000002112A731000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112A761000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.DependencyInjection.dll - Access violation at 00007FFE5021AD7C accessing 000002112A771000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.Tracing.dll - Access violation at 00007FFE5021AD7C accessing 000002112A791000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.dll - Access violation at 00007FFE5021AD7C accessing 000001D0928B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.EnvironmentVariables.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.CommandLine.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7C1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Primitives.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7D1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.FileProviders.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7E1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.FileProviders.Physical.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7F1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.FileExtensions.dll - Access violation at 00007FFE5021AD7C accessing 000002112D981000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.Json.dll - Access violation at 00007FFE5021AD7C accessing 000002112D991000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.UserSecrets.dll - Access violation at 00007FFE5021AD7C accessing 000002112D9A1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Configuration.Binder.dll - Access violation at 00007FFE5021AD7C accessing 000002112D9B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.FileSystemGlobbing.dll - Access violation at 00007FFE5021AD7C accessing 000002112D9C1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Overlapped.dll - Access violation at 00007FFE5021AD7C accessing 000002112D9D1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\Microsoft.Win32.Primitives.dll - Access violation at 00007FFE5021AD7C accessing 000002112DCD1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Options.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD01000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.dll - Access violation at 00007FFE5021AD7C accessing 000002112A7A1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Diagnostics.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD21000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD31000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Diagnostics.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD51000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.Configuration.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD61000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.Debug.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD71000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.EventSource.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD81000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.EventLog.dll - Access violation at 00007FFE5021AD7C accessing 000002112DD91000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Logging.Console.dll - Access violation at 00007FFE5021AD7C accessing 000002112DDA1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Options.ConfigurationExtensions.dll - Access violation at 00007FFE5021AD7C accessing 000002112DDC1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Scrutor.dll - Access violation at 00007FFE5021AD7C accessing 000002112DDE1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Serilog.Extensions.Logging.dll - Access violation at 00007FFE5021AD7C accessing 000001D095871000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Serilog.Sinks.Console.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE01000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Serilog.Sinks.File.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE11000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.IO.FileSystem.dll - Access violation at 00007FFE5021AD7C accessing 000002112DDD1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.Lightweight.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE41000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.ILGeneration.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE51000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Primitives.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE61000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.Localization.Abstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112DCE1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.ThreadPool.dll - Access violation at 00007FFE5021AD7C accessing 000002112DCF1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Text.Encoding.Extensions.dll - Access violation at 00007FFE5021AD7C accessing 000002112DEE1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Intrinsics.dll - Access violation at 00007FFE5021AD7C accessing 000002112DE81000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Numerics.Vectors.dll - Access violation at 00007FFE5021AD7C accessing 000002112F181000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Loader.dll - Access violation at 00007FFE5021AD7C accessing 000002112F171000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\McMaster.NETCore.Plugins.dll - Access violation at 00007FFE5021AD7C accessing 000002112F191000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Extensions.dll - Access violation at 00007FFE5021AD7C accessing 000002112F1A1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.Extensions.DependencyModel.dll - Access violation at 00007FFE5021AD7C accessing 000002112F1C1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.XDocument.dll - Access violation at 00007FFE5021AD7C accessing 000002112EAB1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Resources.ResourceManager.dll - Access violation at 00007FFE5021AD7C accessing 000002112F1B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.Debug.dll - Access violation at 00007FFE5021AD7C accessing 000002112F401000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.InteropServices.RuntimeInformation.dll - Access violation at 00007FFE5021AD7C accessing 000002112F411000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Tasks.dll - Access violation at 00007FFE5021AD7C accessing 000002112F421000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\Microsoft.DotNet.PlatformAbstractions.dll - Access violation at 00007FFE5021AD7C accessing 000002112F431000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\netstandard.dll - Access violation at 00007FFE5021AD7C accessing 000002112F441000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Buffers.dll - Access violation at 00007FFE5021AD7C accessing 000002112F461000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Thread.dll - Access violation at 00007FFE5021AD7C accessing 000002112F471000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\api\runtimes\win\lib\net8.0\System.Diagnostics.EventLog.dll - Access violation at 00007FFE5021AD7C accessing 000002112F481000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.Contracts.dll - Access violation at 00007FFE5021AD7C accessing 000002112F4B1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Serialization.Xml.dll - Access violation at 00007FFE5021AD7C accessing 000002112F4C1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Serialization.Json.dll - Access violation at 00007FFE5021AD7C accessing 000002112F4D1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.ReaderWriter.dll - Access violation at 00007FFE5021AD7C accessing 000002112F4E1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.XmlSerializer.dll - Access violation at 00007FFE5021AD7C accessing 000002112F4F1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Xml.XPath.dll - Access violation at 00007FFE5021AD7C accessing 000002112F501000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\shared\CS2-CustomVotes.Shared\CS2-CustomVotes.Shared.dll - Access violation at 00007FFE5021AD7C accessing 000002112EAA1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\shared\GunGameAPI\GunGameAPI.dll - Access violation at 00007FFE5021AD7C accessing 000002112F731000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\shared\K4-ArenaSharedApi\K4-ArenaSharedApi.dll - Access violation at 00007FFE5021AD7C accessing 000002112F1E1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\shared\RetakesPluginShared\RetakesPluginShared.dll - Access violation at 00007FFE5021AD7C accessing 000002112F521000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\mscorlib.dll - Access violation at 00007FFE5021AD7C accessing 000002112FDF1000.
Could not PreloadLibrary C:\CS2Server\server\game\csgo\addons\counterstrikesharp\dotnet\shared\Microsoft.NETCore.App\8.0.3\System.Core.dll - Access violation at 00007FFE5021AD7C accessing 000002112FE11000."

**Comment by TheEnergy** [comment]
It works now after latest update. Stille getting alle these errors.

**Comment by IvanArsenev** [comment]
Hey guys, I'm getting the same error, have you figured out how to solve it yet?

**Comment by IvanArsenev** [comment]
I do not know how, but I was able to copy some logs, maybe this will help solve the problem?
[log.txt](https://github.com/user-attachments/files/16837918/log.txt)

**Comment by IvanArsenev** [comment]
I managed to fix the error by installing steam and logging into my account on the server computer
